language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
  - npm run build-doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master
jobs:
  include:
    - stage: npm publish
      node_js: 
        - "stable"
      script: yarn build
      deploy:
        provider: npm
        email: "$npm_email"
        api_key: "$npm_token"
        skip_cleanup: true
        on:
          branch: master